### PR TITLE
feat(line-length-checker): show file path instead of only file name

### LINKED ISSUE #4: LineLengthChecker: Show relative path instead of only file name
If the same class exists in multiple packages it is hard to understand which one has the line length violation. It would be better to show the full relative path.

### PR DESCRIPTION
**Pull request by chrisknedl**
# Important: PR https://github.com/uni-passau-artemis/pipeline-helper/pull/7 is based on this branch.
Closes #4.

### CODE REVIEW

**Comment by b-fein** [comment]
From the Jenkins pipeline the checker is started like
```bash
java -jar ./pipeline-helper.jar line-length -l 80 -s assignment/ -e java
```

This results in
```json
{
    "name": "LineLengthChecker",
    "successful": false,
    "message": "Found files with lines longer than 80 characters:\nassignment/src/sudoku/model/Board.java: 1 lines"
}
```

⇒ works.

Possible enhancement: Can you make the path relative to the path given via the `-s` CLI argument, rather than relative to the current working directory?

**Comment by chrisknedl** [comment]
The `\n` is very ugly, though. Will have a look at the code again with your suggestion in mind.

**Comment by b-fein** [comment]
The `\n` is just how the text has to be escaped inside the JSON. In the output shown to the user there is a proper newline character.

**Comment by chrisknedl** [comment]
Oh I see.

**Review by b-fein — APPROVED** [review]

**Pull request merged**
